# Generated by Django 4.2.4 on 2024-01-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=10)),
                ('mother_board', models.CharField(max_length=200)),
                ('memory', models.CharField(max_length=10)),
                ('budget_year', models.IntegerField()),
                ('others', models.CharField(max_length=200)),
            ],
        ),
    ]
